# Generated by Django 4.2.16 on 2024-10-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonpasswords',
            name='passwordID',
        ),
    ]
