# Generated by Django 4.2.16 on 2024-10-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSA', '0003_common_passwords_delete_commonpasswords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_passwords',
            name='content',
            field=models.TextField(),
        ),
    ]
